// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: output.proto

package debs.challenge.msg;

public final class COutputMessages {
  private COutputMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CAlarmOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required fixed64 ts = 1;
    boolean hasTs();
    long getTs();
    
    // required uint32 opCode = 2;
    boolean hasOpCode();
    int getOpCode();
  }
  public static final class CAlarm extends
      com.google.protobuf.GeneratedMessage
      implements CAlarmOrBuilder {
    // Use CAlarm.newBuilder() to construct.
    private CAlarm(Builder builder) {
      super(builder);
    }
    private CAlarm(boolean noInit) {}
    
    private static final CAlarm defaultInstance;
    public static CAlarm getDefaultInstance() {
      return defaultInstance;
    }
    
    public CAlarm getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CAlarm_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CAlarm_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required fixed64 ts = 1;
    public static final int TS_FIELD_NUMBER = 1;
    private long ts_;
    public boolean hasTs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTs() {
      return ts_;
    }
    
    // required uint32 opCode = 2;
    public static final int OPCODE_FIELD_NUMBER = 2;
    private int opCode_;
    public boolean hasOpCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getOpCode() {
      return opCode_;
    }
    
    private void initFields() {
      ts_ = 0L;
      opCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, ts_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, opCode_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, ts_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, opCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static debs.challenge.msg.COutputMessages.CAlarm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CAlarm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CAlarm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CAlarm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CAlarm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CAlarm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CAlarm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static debs.challenge.msg.COutputMessages.CAlarm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static debs.challenge.msg.COutputMessages.CAlarm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CAlarm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(debs.challenge.msg.COutputMessages.CAlarm prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements debs.challenge.msg.COutputMessages.CAlarmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CAlarm_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CAlarm_fieldAccessorTable;
      }
      
      // Construct using debs.challenge.msg.COutputMessages.CAlarm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        opCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return debs.challenge.msg.COutputMessages.CAlarm.getDescriptor();
      }
      
      public debs.challenge.msg.COutputMessages.CAlarm getDefaultInstanceForType() {
        return debs.challenge.msg.COutputMessages.CAlarm.getDefaultInstance();
      }
      
      public debs.challenge.msg.COutputMessages.CAlarm build() {
        debs.challenge.msg.COutputMessages.CAlarm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private debs.challenge.msg.COutputMessages.CAlarm buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        debs.challenge.msg.COutputMessages.CAlarm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public debs.challenge.msg.COutputMessages.CAlarm buildPartial() {
        debs.challenge.msg.COutputMessages.CAlarm result = new debs.challenge.msg.COutputMessages.CAlarm(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.opCode_ = opCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof debs.challenge.msg.COutputMessages.CAlarm) {
          return mergeFrom((debs.challenge.msg.COutputMessages.CAlarm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(debs.challenge.msg.COutputMessages.CAlarm other) {
        if (other == debs.challenge.msg.COutputMessages.CAlarm.getDefaultInstance()) return this;
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasOpCode()) {
          setOpCode(other.getOpCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTs()) {
          
          return false;
        }
        if (!hasOpCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              ts_ = input.readFixed64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              opCode_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required fixed64 ts = 1;
      private long ts_ ;
      public boolean hasTs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTs() {
        return ts_;
      }
      public Builder setTs(long value) {
        bitField0_ |= 0x00000001;
        ts_ = value;
        onChanged();
        return this;
      }
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        onChanged();
        return this;
      }
      
      // required uint32 opCode = 2;
      private int opCode_ ;
      public boolean hasOpCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getOpCode() {
        return opCode_;
      }
      public Builder setOpCode(int value) {
        bitField0_ |= 0x00000002;
        opCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        opCode_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:debs.challenge.msg.CAlarm)
    }
    
    static {
      defaultInstance = new CAlarm(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:debs.challenge.msg.CAlarm)
  }
  
  public interface CPlotOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required fixed64 ts = 1;
    boolean hasTs();
    long getTs();
    
    // required uint32 opCode = 2;
    boolean hasOpCode();
    int getOpCode();
    
    // required uint32 slope = 3;
    boolean hasSlope();
    int getSlope();
    
    // required uint32 intercept = 4;
    boolean hasIntercept();
    int getIntercept();
  }
  public static final class CPlot extends
      com.google.protobuf.GeneratedMessage
      implements CPlotOrBuilder {
    // Use CPlot.newBuilder() to construct.
    private CPlot(Builder builder) {
      super(builder);
    }
    private CPlot(boolean noInit) {}
    
    private static final CPlot defaultInstance;
    public static CPlot getDefaultInstance() {
      return defaultInstance;
    }
    
    public CPlot getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CPlot_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CPlot_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required fixed64 ts = 1;
    public static final int TS_FIELD_NUMBER = 1;
    private long ts_;
    public boolean hasTs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTs() {
      return ts_;
    }
    
    // required uint32 opCode = 2;
    public static final int OPCODE_FIELD_NUMBER = 2;
    private int opCode_;
    public boolean hasOpCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getOpCode() {
      return opCode_;
    }
    
    // required uint32 slope = 3;
    public static final int SLOPE_FIELD_NUMBER = 3;
    private int slope_;
    public boolean hasSlope() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getSlope() {
      return slope_;
    }
    
    // required uint32 intercept = 4;
    public static final int INTERCEPT_FIELD_NUMBER = 4;
    private int intercept_;
    public boolean hasIntercept() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getIntercept() {
      return intercept_;
    }
    
    private void initFields() {
      ts_ = 0L;
      opCode_ = 0;
      slope_ = 0;
      intercept_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSlope()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIntercept()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, ts_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, opCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, slope_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, intercept_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, ts_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, opCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, slope_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, intercept_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static debs.challenge.msg.COutputMessages.CPlot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPlot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPlot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPlot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPlot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPlot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPlot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static debs.challenge.msg.COutputMessages.CPlot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static debs.challenge.msg.COutputMessages.CPlot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPlot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(debs.challenge.msg.COutputMessages.CPlot prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements debs.challenge.msg.COutputMessages.CPlotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CPlot_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CPlot_fieldAccessorTable;
      }
      
      // Construct using debs.challenge.msg.COutputMessages.CPlot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        opCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        slope_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        intercept_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return debs.challenge.msg.COutputMessages.CPlot.getDescriptor();
      }
      
      public debs.challenge.msg.COutputMessages.CPlot getDefaultInstanceForType() {
        return debs.challenge.msg.COutputMessages.CPlot.getDefaultInstance();
      }
      
      public debs.challenge.msg.COutputMessages.CPlot build() {
        debs.challenge.msg.COutputMessages.CPlot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private debs.challenge.msg.COutputMessages.CPlot buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        debs.challenge.msg.COutputMessages.CPlot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public debs.challenge.msg.COutputMessages.CPlot buildPartial() {
        debs.challenge.msg.COutputMessages.CPlot result = new debs.challenge.msg.COutputMessages.CPlot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.opCode_ = opCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.slope_ = slope_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.intercept_ = intercept_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof debs.challenge.msg.COutputMessages.CPlot) {
          return mergeFrom((debs.challenge.msg.COutputMessages.CPlot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(debs.challenge.msg.COutputMessages.CPlot other) {
        if (other == debs.challenge.msg.COutputMessages.CPlot.getDefaultInstance()) return this;
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasOpCode()) {
          setOpCode(other.getOpCode());
        }
        if (other.hasSlope()) {
          setSlope(other.getSlope());
        }
        if (other.hasIntercept()) {
          setIntercept(other.getIntercept());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTs()) {
          
          return false;
        }
        if (!hasOpCode()) {
          
          return false;
        }
        if (!hasSlope()) {
          
          return false;
        }
        if (!hasIntercept()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              ts_ = input.readFixed64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              opCode_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              slope_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              intercept_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required fixed64 ts = 1;
      private long ts_ ;
      public boolean hasTs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTs() {
        return ts_;
      }
      public Builder setTs(long value) {
        bitField0_ |= 0x00000001;
        ts_ = value;
        onChanged();
        return this;
      }
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        onChanged();
        return this;
      }
      
      // required uint32 opCode = 2;
      private int opCode_ ;
      public boolean hasOpCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getOpCode() {
        return opCode_;
      }
      public Builder setOpCode(int value) {
        bitField0_ |= 0x00000002;
        opCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        opCode_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 slope = 3;
      private int slope_ ;
      public boolean hasSlope() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getSlope() {
        return slope_;
      }
      public Builder setSlope(int value) {
        bitField0_ |= 0x00000004;
        slope_ = value;
        onChanged();
        return this;
      }
      public Builder clearSlope() {
        bitField0_ = (bitField0_ & ~0x00000004);
        slope_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 intercept = 4;
      private int intercept_ ;
      public boolean hasIntercept() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getIntercept() {
        return intercept_;
      }
      public Builder setIntercept(int value) {
        bitField0_ |= 0x00000008;
        intercept_ = value;
        onChanged();
        return this;
      }
      public Builder clearIntercept() {
        bitField0_ = (bitField0_ & ~0x00000008);
        intercept_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:debs.challenge.msg.CPlot)
    }
    
    static {
      defaultInstance = new CPlot(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:debs.challenge.msg.CPlot)
  }
  
  public interface CPowerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required fixed64 ts = 1;
    boolean hasTs();
    long getTs();
    
    // required float power1 = 2;
    boolean hasPower1();
    float getPower1();
    
    // required float power2 = 3;
    boolean hasPower2();
    float getPower2();
    
    // required float power3 = 4;
    boolean hasPower3();
    float getPower3();
  }
  public static final class CPower extends
      com.google.protobuf.GeneratedMessage
      implements CPowerOrBuilder {
    // Use CPower.newBuilder() to construct.
    private CPower(Builder builder) {
      super(builder);
    }
    private CPower(boolean noInit) {}
    
    private static final CPower defaultInstance;
    public static CPower getDefaultInstance() {
      return defaultInstance;
    }
    
    public CPower getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CPower_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CPower_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required fixed64 ts = 1;
    public static final int TS_FIELD_NUMBER = 1;
    private long ts_;
    public boolean hasTs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTs() {
      return ts_;
    }
    
    // required float power1 = 2;
    public static final int POWER1_FIELD_NUMBER = 2;
    private float power1_;
    public boolean hasPower1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getPower1() {
      return power1_;
    }
    
    // required float power2 = 3;
    public static final int POWER2_FIELD_NUMBER = 3;
    private float power2_;
    public boolean hasPower2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getPower2() {
      return power2_;
    }
    
    // required float power3 = 4;
    public static final int POWER3_FIELD_NUMBER = 4;
    private float power3_;
    public boolean hasPower3() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getPower3() {
      return power3_;
    }
    
    private void initFields() {
      ts_ = 0L;
      power1_ = 0F;
      power2_ = 0F;
      power3_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPower1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPower2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPower3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, ts_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, power1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, power2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, power3_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, ts_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, power1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, power2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, power3_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static debs.challenge.msg.COutputMessages.CPower parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPower parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPower parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPower parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPower parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPower parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPower parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static debs.challenge.msg.COutputMessages.CPower parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static debs.challenge.msg.COutputMessages.CPower parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CPower parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(debs.challenge.msg.COutputMessages.CPower prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements debs.challenge.msg.COutputMessages.CPowerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CPower_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CPower_fieldAccessorTable;
      }
      
      // Construct using debs.challenge.msg.COutputMessages.CPower.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        power1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        power2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        power3_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return debs.challenge.msg.COutputMessages.CPower.getDescriptor();
      }
      
      public debs.challenge.msg.COutputMessages.CPower getDefaultInstanceForType() {
        return debs.challenge.msg.COutputMessages.CPower.getDefaultInstance();
      }
      
      public debs.challenge.msg.COutputMessages.CPower build() {
        debs.challenge.msg.COutputMessages.CPower result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private debs.challenge.msg.COutputMessages.CPower buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        debs.challenge.msg.COutputMessages.CPower result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public debs.challenge.msg.COutputMessages.CPower buildPartial() {
        debs.challenge.msg.COutputMessages.CPower result = new debs.challenge.msg.COutputMessages.CPower(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.power1_ = power1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.power2_ = power2_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.power3_ = power3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof debs.challenge.msg.COutputMessages.CPower) {
          return mergeFrom((debs.challenge.msg.COutputMessages.CPower)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(debs.challenge.msg.COutputMessages.CPower other) {
        if (other == debs.challenge.msg.COutputMessages.CPower.getDefaultInstance()) return this;
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasPower1()) {
          setPower1(other.getPower1());
        }
        if (other.hasPower2()) {
          setPower2(other.getPower2());
        }
        if (other.hasPower3()) {
          setPower3(other.getPower3());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTs()) {
          
          return false;
        }
        if (!hasPower1()) {
          
          return false;
        }
        if (!hasPower2()) {
          
          return false;
        }
        if (!hasPower3()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              ts_ = input.readFixed64();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              power1_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              power2_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              power3_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required fixed64 ts = 1;
      private long ts_ ;
      public boolean hasTs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTs() {
        return ts_;
      }
      public Builder setTs(long value) {
        bitField0_ |= 0x00000001;
        ts_ = value;
        onChanged();
        return this;
      }
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        onChanged();
        return this;
      }
      
      // required float power1 = 2;
      private float power1_ ;
      public boolean hasPower1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getPower1() {
        return power1_;
      }
      public Builder setPower1(float value) {
        bitField0_ |= 0x00000002;
        power1_ = value;
        onChanged();
        return this;
      }
      public Builder clearPower1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        power1_ = 0F;
        onChanged();
        return this;
      }
      
      // required float power2 = 3;
      private float power2_ ;
      public boolean hasPower2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getPower2() {
        return power2_;
      }
      public Builder setPower2(float value) {
        bitField0_ |= 0x00000004;
        power2_ = value;
        onChanged();
        return this;
      }
      public Builder clearPower2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        power2_ = 0F;
        onChanged();
        return this;
      }
      
      // required float power3 = 4;
      private float power3_ ;
      public boolean hasPower3() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getPower3() {
        return power3_;
      }
      public Builder setPower3(float value) {
        bitField0_ |= 0x00000008;
        power3_ = value;
        onChanged();
        return this;
      }
      public Builder clearPower3() {
        bitField0_ = (bitField0_ & ~0x00000008);
        power3_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:debs.challenge.msg.CPower)
    }
    
    static {
      defaultInstance = new CPower(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:debs.challenge.msg.CPower)
  }
  
  public interface CViolationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required fixed64 ts = 1;
    boolean hasTs();
    long getTs();
    
    // required float mf01Avg = 2;
    boolean hasMf01Avg();
    float getMf01Avg();
    
    // required float mf02Avg = 3;
    boolean hasMf02Avg();
    float getMf02Avg();
    
    // required float mf03Avg = 4;
    boolean hasMf03Avg();
    float getMf03Avg();
    
    // required float mf01Rng = 5;
    boolean hasMf01Rng();
    float getMf01Rng();
    
    // required float mf02Rng = 6;
    boolean hasMf02Rng();
    float getMf02Rng();
    
    // required float mf03Rng = 7;
    boolean hasMf03Rng();
    float getMf03Rng();
  }
  public static final class CViolation extends
      com.google.protobuf.GeneratedMessage
      implements CViolationOrBuilder {
    // Use CViolation.newBuilder() to construct.
    private CViolation(Builder builder) {
      super(builder);
    }
    private CViolation(boolean noInit) {}
    
    private static final CViolation defaultInstance;
    public static CViolation getDefaultInstance() {
      return defaultInstance;
    }
    
    public CViolation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CViolation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CViolation_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required fixed64 ts = 1;
    public static final int TS_FIELD_NUMBER = 1;
    private long ts_;
    public boolean hasTs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTs() {
      return ts_;
    }
    
    // required float mf01Avg = 2;
    public static final int MF01AVG_FIELD_NUMBER = 2;
    private float mf01Avg_;
    public boolean hasMf01Avg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getMf01Avg() {
      return mf01Avg_;
    }
    
    // required float mf02Avg = 3;
    public static final int MF02AVG_FIELD_NUMBER = 3;
    private float mf02Avg_;
    public boolean hasMf02Avg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getMf02Avg() {
      return mf02Avg_;
    }
    
    // required float mf03Avg = 4;
    public static final int MF03AVG_FIELD_NUMBER = 4;
    private float mf03Avg_;
    public boolean hasMf03Avg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getMf03Avg() {
      return mf03Avg_;
    }
    
    // required float mf01Rng = 5;
    public static final int MF01RNG_FIELD_NUMBER = 5;
    private float mf01Rng_;
    public boolean hasMf01Rng() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public float getMf01Rng() {
      return mf01Rng_;
    }
    
    // required float mf02Rng = 6;
    public static final int MF02RNG_FIELD_NUMBER = 6;
    private float mf02Rng_;
    public boolean hasMf02Rng() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public float getMf02Rng() {
      return mf02Rng_;
    }
    
    // required float mf03Rng = 7;
    public static final int MF03RNG_FIELD_NUMBER = 7;
    private float mf03Rng_;
    public boolean hasMf03Rng() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public float getMf03Rng() {
      return mf03Rng_;
    }
    
    private void initFields() {
      ts_ = 0L;
      mf01Avg_ = 0F;
      mf02Avg_ = 0F;
      mf03Avg_ = 0F;
      mf01Rng_ = 0F;
      mf02Rng_ = 0F;
      mf03Rng_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMf01Avg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMf02Avg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMf03Avg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMf01Rng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMf02Rng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMf03Rng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, ts_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, mf01Avg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, mf02Avg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, mf03Avg_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, mf01Rng_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, mf02Rng_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, mf03Rng_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, ts_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, mf01Avg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, mf02Avg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, mf03Avg_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, mf01Rng_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, mf02Rng_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, mf03Rng_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static debs.challenge.msg.COutputMessages.CViolation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CViolation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CViolation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CViolation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CViolation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CViolation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CViolation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static debs.challenge.msg.COutputMessages.CViolation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static debs.challenge.msg.COutputMessages.CViolation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static debs.challenge.msg.COutputMessages.CViolation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(debs.challenge.msg.COutputMessages.CViolation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements debs.challenge.msg.COutputMessages.CViolationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CViolation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return debs.challenge.msg.COutputMessages.internal_static_debs_challenge_msg_CViolation_fieldAccessorTable;
      }
      
      // Construct using debs.challenge.msg.COutputMessages.CViolation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        mf01Avg_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        mf02Avg_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        mf03Avg_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        mf01Rng_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        mf02Rng_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        mf03Rng_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return debs.challenge.msg.COutputMessages.CViolation.getDescriptor();
      }
      
      public debs.challenge.msg.COutputMessages.CViolation getDefaultInstanceForType() {
        return debs.challenge.msg.COutputMessages.CViolation.getDefaultInstance();
      }
      
      public debs.challenge.msg.COutputMessages.CViolation build() {
        debs.challenge.msg.COutputMessages.CViolation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private debs.challenge.msg.COutputMessages.CViolation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        debs.challenge.msg.COutputMessages.CViolation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public debs.challenge.msg.COutputMessages.CViolation buildPartial() {
        debs.challenge.msg.COutputMessages.CViolation result = new debs.challenge.msg.COutputMessages.CViolation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mf01Avg_ = mf01Avg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mf02Avg_ = mf02Avg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mf03Avg_ = mf03Avg_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mf01Rng_ = mf01Rng_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.mf02Rng_ = mf02Rng_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.mf03Rng_ = mf03Rng_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof debs.challenge.msg.COutputMessages.CViolation) {
          return mergeFrom((debs.challenge.msg.COutputMessages.CViolation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(debs.challenge.msg.COutputMessages.CViolation other) {
        if (other == debs.challenge.msg.COutputMessages.CViolation.getDefaultInstance()) return this;
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasMf01Avg()) {
          setMf01Avg(other.getMf01Avg());
        }
        if (other.hasMf02Avg()) {
          setMf02Avg(other.getMf02Avg());
        }
        if (other.hasMf03Avg()) {
          setMf03Avg(other.getMf03Avg());
        }
        if (other.hasMf01Rng()) {
          setMf01Rng(other.getMf01Rng());
        }
        if (other.hasMf02Rng()) {
          setMf02Rng(other.getMf02Rng());
        }
        if (other.hasMf03Rng()) {
          setMf03Rng(other.getMf03Rng());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTs()) {
          
          return false;
        }
        if (!hasMf01Avg()) {
          
          return false;
        }
        if (!hasMf02Avg()) {
          
          return false;
        }
        if (!hasMf03Avg()) {
          
          return false;
        }
        if (!hasMf01Rng()) {
          
          return false;
        }
        if (!hasMf02Rng()) {
          
          return false;
        }
        if (!hasMf03Rng()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              ts_ = input.readFixed64();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              mf01Avg_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              mf02Avg_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              mf03Avg_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              mf01Rng_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              mf02Rng_ = input.readFloat();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              mf03Rng_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required fixed64 ts = 1;
      private long ts_ ;
      public boolean hasTs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTs() {
        return ts_;
      }
      public Builder setTs(long value) {
        bitField0_ |= 0x00000001;
        ts_ = value;
        onChanged();
        return this;
      }
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        onChanged();
        return this;
      }
      
      // required float mf01Avg = 2;
      private float mf01Avg_ ;
      public boolean hasMf01Avg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getMf01Avg() {
        return mf01Avg_;
      }
      public Builder setMf01Avg(float value) {
        bitField0_ |= 0x00000002;
        mf01Avg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMf01Avg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mf01Avg_ = 0F;
        onChanged();
        return this;
      }
      
      // required float mf02Avg = 3;
      private float mf02Avg_ ;
      public boolean hasMf02Avg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getMf02Avg() {
        return mf02Avg_;
      }
      public Builder setMf02Avg(float value) {
        bitField0_ |= 0x00000004;
        mf02Avg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMf02Avg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mf02Avg_ = 0F;
        onChanged();
        return this;
      }
      
      // required float mf03Avg = 4;
      private float mf03Avg_ ;
      public boolean hasMf03Avg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getMf03Avg() {
        return mf03Avg_;
      }
      public Builder setMf03Avg(float value) {
        bitField0_ |= 0x00000008;
        mf03Avg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMf03Avg() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mf03Avg_ = 0F;
        onChanged();
        return this;
      }
      
      // required float mf01Rng = 5;
      private float mf01Rng_ ;
      public boolean hasMf01Rng() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public float getMf01Rng() {
        return mf01Rng_;
      }
      public Builder setMf01Rng(float value) {
        bitField0_ |= 0x00000010;
        mf01Rng_ = value;
        onChanged();
        return this;
      }
      public Builder clearMf01Rng() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mf01Rng_ = 0F;
        onChanged();
        return this;
      }
      
      // required float mf02Rng = 6;
      private float mf02Rng_ ;
      public boolean hasMf02Rng() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public float getMf02Rng() {
        return mf02Rng_;
      }
      public Builder setMf02Rng(float value) {
        bitField0_ |= 0x00000020;
        mf02Rng_ = value;
        onChanged();
        return this;
      }
      public Builder clearMf02Rng() {
        bitField0_ = (bitField0_ & ~0x00000020);
        mf02Rng_ = 0F;
        onChanged();
        return this;
      }
      
      // required float mf03Rng = 7;
      private float mf03Rng_ ;
      public boolean hasMf03Rng() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public float getMf03Rng() {
        return mf03Rng_;
      }
      public Builder setMf03Rng(float value) {
        bitField0_ |= 0x00000040;
        mf03Rng_ = value;
        onChanged();
        return this;
      }
      public Builder clearMf03Rng() {
        bitField0_ = (bitField0_ & ~0x00000040);
        mf03Rng_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:debs.challenge.msg.CViolation)
    }
    
    static {
      defaultInstance = new CViolation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:debs.challenge.msg.CViolation)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_debs_challenge_msg_CAlarm_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_debs_challenge_msg_CAlarm_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_debs_challenge_msg_CPlot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_debs_challenge_msg_CPlot_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_debs_challenge_msg_CPower_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_debs_challenge_msg_CPower_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_debs_challenge_msg_CViolation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_debs_challenge_msg_CViolation_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014output.proto\022\022debs.challenge.msg\"$\n\006CA" +
      "larm\022\n\n\002ts\030\001 \002(\006\022\016\n\006opCode\030\002 \002(\r\"E\n\005CPlo" +
      "t\022\n\n\002ts\030\001 \002(\006\022\016\n\006opCode\030\002 \002(\r\022\r\n\005slope\030\003" +
      " \002(\r\022\021\n\tintercept\030\004 \002(\r\"D\n\006CPower\022\n\n\002ts\030" +
      "\001 \002(\006\022\016\n\006power1\030\002 \002(\002\022\016\n\006power2\030\003 \002(\002\022\016\n" +
      "\006power3\030\004 \002(\002\"~\n\nCViolation\022\n\n\002ts\030\001 \002(\006\022" +
      "\017\n\007mf01Avg\030\002 \002(\002\022\017\n\007mf02Avg\030\003 \002(\002\022\017\n\007mf0" +
      "3Avg\030\004 \002(\002\022\017\n\007mf01Rng\030\005 \002(\002\022\017\n\007mf02Rng\030\006" +
      " \002(\002\022\017\n\007mf03Rng\030\007 \002(\002B\023B\017COutputMessages" +
      "H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_debs_challenge_msg_CAlarm_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_debs_challenge_msg_CAlarm_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_debs_challenge_msg_CAlarm_descriptor,
              new java.lang.String[] { "Ts", "OpCode", },
              debs.challenge.msg.COutputMessages.CAlarm.class,
              debs.challenge.msg.COutputMessages.CAlarm.Builder.class);
          internal_static_debs_challenge_msg_CPlot_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_debs_challenge_msg_CPlot_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_debs_challenge_msg_CPlot_descriptor,
              new java.lang.String[] { "Ts", "OpCode", "Slope", "Intercept", },
              debs.challenge.msg.COutputMessages.CPlot.class,
              debs.challenge.msg.COutputMessages.CPlot.Builder.class);
          internal_static_debs_challenge_msg_CPower_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_debs_challenge_msg_CPower_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_debs_challenge_msg_CPower_descriptor,
              new java.lang.String[] { "Ts", "Power1", "Power2", "Power3", },
              debs.challenge.msg.COutputMessages.CPower.class,
              debs.challenge.msg.COutputMessages.CPower.Builder.class);
          internal_static_debs_challenge_msg_CViolation_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_debs_challenge_msg_CViolation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_debs_challenge_msg_CViolation_descriptor,
              new java.lang.String[] { "Ts", "Mf01Avg", "Mf02Avg", "Mf03Avg", "Mf01Rng", "Mf02Rng", "Mf03Rng", },
              debs.challenge.msg.COutputMessages.CViolation.class,
              debs.challenge.msg.COutputMessages.CViolation.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
